# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_api_order_item_create:
    path: /
    methods: [POST]
    defaults:
        _controller: sylius.controller.order_item:createAction
        _sylius:
            serialization_version: $version
            form: Sylius\Bundle\ApiBundle\Form\Type\OrderItemType
            factory:
                method: createForCart
                arguments:
                  - expr:service('sylius.repository.order').find($cartId)

sylius_api_order_item_update:
    path: /{id}
    methods: [PUT, PATCH]
    defaults:
        _controller: sylius.controller.order_item:updateAction
        _sylius:
            serialization_version: $version
            form: Sylius\Bundle\ApiBundle\Form\Type\OrderItemType
            criteria:
                order: $orderId

sylius_api_order_item_delete:
    path: /{id}
    methods: [DELETE]
    defaults:
        _controller: sylius.controller.order_item:deleteAction
        _sylius:
            serialization_version: $version
            criteria:
                order: $orderId
            csrf_protection: false
