# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_api_cart_item_create:
    path: /items/
    methods: [POST]
    defaults:
        _controller: sylius.controller.order_item:createAction
        _sylius:
            serialization_version: $version
            form: Sylius\Bundle\ApiBundle\Form\Type\OrderItemType
            factory:
                method: createForCart
                arguments:
                  - "expr:notFoundOnNull(service('sylius.repository.order').findCartById($cartId))"
            serialization_groups: [DetailedCart]

sylius_api_cart_item:
    resource: |
        alias: sylius.order_item
        path: 'items'
        only: [update, delete]
        section: api
        form: Sylius\Bundle\ApiBundle\Form\Type\OrderItemType
        serialization_version: $version
        criteria:
            cart: $cartId
    type: sylius.resource_api
