# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_api_cart_index:
    path: /
    methods: [GET]
    defaults:
        _controller: sylius.controller.order:indexAction
        _sylius:
            serialization_version: $version
            paginate: $limit
            sortable: true
            grid: sylius_api_cart

sylius_api_cart_create:
    path: /
    methods: [POST]
    defaults:
        _controller: sylius.controller.order:createAction
        _sylius:
            serialization_version: $version
            form: Sylius\Bundle\ApiBundle\Form\Type\OrderType

sylius_api_cart_delete:
    path: /{id}
    methods: [DELETE]
    defaults:
        _controller: sylius.controller.order:deleteAction
        _format: json
        _sylius:
            serialization_version: $version
            csrf_protection: false
            repository:
                method: findCartById
                arguments: [$id]

sylius_api_cart_show:
    path: /{id}
    methods: [GET]
    defaults:
        _controller: sylius.controller.order:showAction
        _sylius:
            serialization_version: $version
            repository:
                method: findCartById
                arguments: [$id]
