# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski
#
sylius_api_checkout_index:
    path: /
    methods: [GET]
    defaults:
        _controller: sylius.controller.order:indexAction
        _sylius:
            repository:
                method:    createCheckoutsPaginator
                arguments: [$criteria, $sorting]
            paginate:  $limit
            sortable:  true
            sorting:
                updatedAt: desc

sylius_api_checkout_show:
    path: /{id}
    methods: [GET]
    defaults:
        _controller: sylius.controller.order:showAction

sylius_api_checkout_addressing:
    path: /addressing/{orderId}/{customerId}/
    methods: [PUT]
    defaults:
        _controller: sylius.controller.order:updateAction
        _sylius:
            form:
                type: sylius_shop_checkout_addressing
                options:
                    customer: expr:service('sylius.repository.customer').find($customerId)
            repository:
                method: find
                arguments: [$orderId]
            state_machine:
                graph: sylius_order_checkout
                transition: address
