# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_api_locale:
    resource: |
        identifier: code
        alias: sylius.locale
        section: api
        except: ['update']
        serialization_version: $version
        criteria:
            code: $code
    type: sylius.resource_api
