# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_api_order:
    resource: |
        alias: sylius.order
        section: api
        only: [show]
        grid: sylius_admin_order
        serialization_version: $version
    type: sylius.resource_api

sylius_api_order_cancel:
    path: /orders/{id}/cancel
    methods: [PUT]
    defaults:
        _controller: sylius.controller.order:applyStateMachineTransitionAction
        _sylius:
            section: api
            state_machine:
                graph: sylius_order
                transition: cancel
            return_content: false

sylius_api_order_shipment_ship:
    path: /orders/{orderId}/shipments/{id}/ship
    methods: [PUT]
    defaults:
        _controller: sylius.controller.shipment:updateAction
        _sylius:
            event: ship
            repository:
                method: findOneByOrderId
                arguments:
                    id: $id
                    orderId: $orderId
            state_machine:
                graph: sylius_shipment
                transition: ship
            section: api
            form: Sylius\Bundle\ShippingBundle\Form\Type\ShipmentShipType

sylius_api_order_payment_complete:
    path: /orders/{orderId}/payments/{id}/complete
    methods: [PUT]
    defaults:
        _controller: sylius.controller.payment:applyStateMachineTransitionAction
        _sylius:
            event: complete
            repository:
                method: findOneByOrderId
                arguments:
                    id: $id
                    orderId: $orderId
            state_machine:
                graph: sylius_payment
                transition: complete
            section: api
            return_content: false
