# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_api_payment_method:
    resource: |
        identifier: code
        alias: sylius.payment_method
        section: api
        only: ['show']
        serialization_version: $version
        criteria:
            code: $code
    type: sylius.resource_api
