# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_api_product_option:
    resource: |
        identifier: code
        alias: sylius.product_option
        section: api
        only: ['index', 'show']
        serialization_version: $version
        criteria:
            code: $code
    type: sylius.resource_api
