# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_api_product_variant_index:
    path: /
    methods: [GET]
    defaults:
        _controller: sylius.controller.product_variant:indexAction
        _sylius:
            paginate: $limit
            serialization_version: $version
            grid: sylius_api_product_variant
            section: api
            serialization_group: [Default]
            criteria:
                product: $productId

sylius_api_product_variant_create:
    path: /
    methods: [POST]
    defaults:
        _controller: sylius.controller.product_variant:createAction
        _sylius:
            serialization_version: $version
            form: Sylius\Bundle\ApiBundle\Form\Type\ProductVariantType
            factory:
                method: createForProduct
                arguments:
                  - expr:service('sylius.repository.product').find($productId)

sylius_api_product_variant_update:
    path: /{id}
    methods: [PUT, PATCH]
    defaults:
        _controller: sylius.controller.product_variant:updateAction
        _sylius:
            serialization_version: $version
            form: Sylius\Bundle\ApiBundle\Form\Type\ProductVariantType
            criteria:
                product: $productId
                master: false

sylius_api_product_variant_delete:
    path: /{id}
    methods: [DELETE]
    defaults:
        _controller: sylius.controller.product_variant:deleteAction
        _sylius:
            serialization_version: $version
            criteria:
                product: $productId
                master: false
            csrf_protection: false

sylius_api_product_variant_show:
    path: /{id}
    methods: [GET]
    defaults:
        _controller: sylius.controller.product_variant:showAction
        _sylius:
            serialization_version: $version
            serialization_group: [Default, Detailed]
            criteria:
                product: $productId
                master: false
