# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_api_product:
    resource: |
        alias: sylius.product
        section: api
        except: ['create', 'update']
        grid: sylius_api_product
        serialization_version: $version
    type: sylius.resource_api

sylius_api_product_create:
    path: /products/
    methods: [POST]
    defaults:
        _controller: sylius.controller.product:createAction
        _sylius:
            serialization_version: $version
            form: Sylius\Bundle\ApiBundle\Form\Type\ProductType

sylius_api_product_update:
    path: /products/{id}
    methods: [POST, PUT, PATCH]
    defaults:
        _controller: sylius.controller.product:updateAction
        _sylius:
            serialization_version: $version
            form: Sylius\Bundle\ApiBundle\Form\Type\ProductType
