# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_api_shipping_category:
    resource: |
        identifier: code
        alias: sylius.shipping_category
        section: api
        serialization_version: $version
        criteria:
            code: $code
    type: sylius.resource_api
