# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_api_tax_rate:
    resource: |
        identifier: code
        alias: sylius.tax_rate
        section: api
        only: ['show', 'index']
        serialization_version: $version
        criteria:
            code: $code
    type: sylius.resource_api
