# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_admin_taxon:
    resource: |
        alias: sylius.taxon
        section: api
        form: Sylius\Bundle\TaxonomyBundle\Form\Type\TaxonType
        grid: sylius_api_taxon
        serialization_version: $version
    type: sylius.resource_api
