# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_api_zone_index:
    path: /
    methods: [GET]
    defaults:
        _controller: sylius.controller.zone:indexAction
        _sylius:
            paginate: $limit
            sortable: true

sylius_api_zone_create:
    path: /{type}
    methods: [POST]
    defaults:
        _controller: sylius.controller.zone:createAction
        _sylius:
            factory:
                method: createTyped
                arguments:
                    type: $type

sylius_api_zone_update:
    path: /{code}
    methods: [PUT, PATCH]
    defaults:
        _controller: sylius.controller.zone:updateAction
        _sylius:
            criteria:
                code: $code

sylius_api_zone_delete:
    path: /{code}
    methods: [DELETE]
    defaults:
        _controller: sylius.controller.zone:deleteAction
        _sylius:
            criteria:
                code: $code
            csrf_protection: false

sylius_api_zone_show:
    path: /{code}
    methods: [GET]
    defaults:
        _controller: sylius.controller.zone:showAction
        _sylius:
            criteria:
                code: $code
